#!/usr/bin/env bash
# Usage: ndkenv version-file-write <file> <version>

set -e
[ -n "$NDKENV_DEBUG" ] && set -x

NDKENV_VERSION_FILE="$1"
NDKENV_VERSION="$2"

if [ -z "$NDKENV_VERSION" ] || [ -z "$NDKENV_VERSION_FILE" ]; then
  ndkenv-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
ndkenv-prefix "$NDKENV_VERSION" >/dev/null

# Write the version out to disk.
echo "$NDKENV_VERSION" > "$NDKENV_VERSION_FILE"
