#!/usr/bin/env bash
#
# Summary: Run an executable with the selected NDK version
#
# Usage: ndkenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected NDK
# version's `bin' directory is at the front.
#
# For example, if the currently selected NDK version is 1.9.3-p327:
#   ndkenv exec bundle install
#
# is equivalent to:
#   PATH="$NDKENV_ROOT/versions/1.9.3-p327/bin:$PATH" bundle install

set -e
[ -n "$NDKENV_DEBUG" ] && set -x

# Provide ndkenv completions
if [ "$1" = "--complete" ]; then
  exec ndkenv shims --short
fi

NDKENV_VERSION="$(ndkenv-version-name)"
NDKENV_COMMAND="$1"

if [ -z "$NDKENV_COMMAND" ]; then
  ndkenv-help --usage exec >&2
  exit 1
fi

export NDKENV_VERSION
NDKENV_COMMAND_PATH="$(ndkenv-which "$NDKENV_COMMAND")"
NDKENV_BIN_PATH="${NDKENV_COMMAND_PATH%/*}"

OLDIFS="$IFS"
IFS=$'\n' scripts=(`ndkenv-hooks exec`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

shift 1
if [ "$NDKENV_VERSION" != "system" ]; then
  export PATH="${NDKENV_BIN_PATH}:${PATH}"
fi
exec -a "$NDKENV_COMMAND" "$NDKENV_COMMAND_PATH" "$@"
