#!/usr/bin/env bash
# Summary: Show the current NDK version
set -e
[ -n "$NDKENV_DEBUG" ] && set -x

if [ -z "$NDKENV_VERSION" ]; then
  NDKENV_VERSION_FILE="$(ndkenv-version-file)"
  NDKENV_VERSION="$(ndkenv-version-file-read "$NDKENV_VERSION_FILE" || true)"
fi

if [ -z "$NDKENV_VERSION" ] || [ "$NDKENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${NDKENV_ROOT}/versions/${version}" ]
}

if version_exists "$NDKENV_VERSION"; then
  echo "$NDKENV_VERSION"
else
  echo "ndkenv: version \`$NDKENV_VERSION' is not installed" >&2
  exit 1
fi
