#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export NDKENV_DEBUG=1
  shift
fi

if [ -n "$NDKENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "ndkenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${NDKENV_ROOT}" ]; then
  NDKENV_ROOT="${HOME}/.ndkenv"
else
  NDKENV_ROOT="${NDKENV_ROOT%/}"
fi
export NDKENV_ROOT

if [ -z "${NDKENV_DIR}" ]; then
  NDKENV_DIR="$(pwd)"
else
  cd "$NDKENV_DIR" 2>/dev/null || {
    echo "ndkenv: cannot change working directory to \`$NDKENV_DIR'"
    exit 1
  } >&2
  NDKENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export NDKENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

hook_path="${NDKENV_HOOK_PATH}:${NDKENV_ROOT}/ndkenv.d:/usr/local/etc/ndkenv.d:/etc/ndkenv.d:/usr/lib/ndkenv/hooks"
export NDKENV_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(ndkenv---version)\n$(ndkenv-help)" >&2
  ;;
"-v" )
  exec ndkenv---version
  ;;
* )
  command_path="$(command -v "ndkenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "ndkenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
