#!/usr/bin/env bash
set -e
[ -n "$NDKENV_DEBUG" ] && set -x

# Provide ndkenv completions
if [ "$1" = "--complete" ]; then
  exec ndkenv-rehash --complete
fi

shell="$(basename "${NDKENV_SHELL:-$SHELL}")"

# When ndkenv shell integration is enabled, delegate to ndkenv-rehash,
# then tell the shell to empty its command lookup cache.
ndkenv-rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
