#!/usr/bin/env bash
# Summary: Explain how the current NDK version is set
set -e
[ -n "$NDKENV_DEBUG" ] && set -x

if [ -n "$NDKENV_VERSION" ]; then
  echo "NDKENV_VERSION environment variable"
else
  ndkenv-version-file
fi
