#!/usr/bin/env bash
# Summary: Display prefix for a NDK version
# Usage: ndkenv prefix [<version>]
#
# Displays the directory where a NDK version is installed. If no
# version is given, `ndkenv prefix' displays the location of the
# currently selected version.

set -e
[ -n "$NDKENV_DEBUG" ] && set -x

# Provide ndkenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec ndkenv-versions --bare
fi

if [ -n "$1" ]; then
  export NDKENV_VERSION="$1"
elif [ -z "$NDKENV_VERSION" ]; then
  NDKENV_VERSION="$(ndkenv-version-name)"
fi

if [ "$NDKENV_VERSION" = "system" ]; then
  if NDK_PATH="$(ndkenv-which ndk 2>/dev/null)"; then
    NDK_PATH="${NDK_PATH%/*}"
    echo "${NDK_PATH%/bin}"
    exit
  else
    echo "ndkenv: system version not found in PATH" >&2
    exit 1
  fi
fi

NDKENV_PREFIX_PATH="${NDKENV_ROOT}/versions/${NDKENV_VERSION}"
if [ ! -d "$NDKENV_PREFIX_PATH" ]; then
  echo "ndkenv: version \`${NDKENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$NDKENV_PREFIX_PATH"
