#!/usr/bin/env bash
# Usage: ndkenv completions <command> [arg1 arg2...]

set -e
[ -n "$NDKENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  ndkenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "ndkenv-$COMMAND" || command -v "ndkenv-sh-$COMMAND")"
if grep -iE "^([#%]|--|//) provide ndkenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
