#!/usr/bin/env bash
# Summary: List all NDK versions available to ndkenv
# Usage: ndkenv versions [--bare]
#
# Lists all NDK versions found in `$NDKENV_ROOT/versions/*'.

set -e
[ -n "$NDKENV_DEBUG" ] && set -x

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  current_version=""
  include_system=""
else
  hit_prefix="* "
  miss_prefix="  "
  current_version="$(ndkenv-version-name || true)"
  include_system="1"
fi

print_version() {
  if [ "$1" == "$current_version" ]; then
    echo "${hit_prefix}$(ndkenv-version 2>/dev/null)"
  else
    echo "${miss_prefix}$1"
  fi
}

# Include "system" in the non-bare output, if it exists
if [ -n "$include_system" ] && NDKENV_VERSION=system ndkenv-which ndk >/dev/null 2>&1; then
  print_version system
fi

for path in "${NDKENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    print_version "${path##*/}"
  fi
done
