#!/usr/bin/env bash
#
# Summary: Set or show the global NDK version
#
# Usage: ndkenv global <version>
#
# Sets the global NDK version. You can override the global version at
# any time by setting a directory-specific version with `ndkenv local'
# or by setting the `NDKENV_VERSION' environment variable.
#
# <version> should be a string matching a NDK version known to ndkenv.
# The special version string `system' will use your default system NDK.
# Run `ndkenv versions' for a list of available NDK versions.

set -e
[ -n "$NDKENV_DEBUG" ] && set -x

# Provide ndkenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec ndkenv-versions --bare
fi

NDKENV_VERSION="$1"
NDKENV_VERSION_FILE="${NDKENV_ROOT}/version"

if [ -n "$NDKENV_VERSION" ]; then
  ndkenv-version-file-write "$NDKENV_VERSION_FILE" "$NDKENV_VERSION"
else
  ndkenv-version-file-read "$NDKENV_VERSION_FILE" ||
  ndkenv-version-file-read "${NDKENV_ROOT}/global" ||
  ndkenv-version-file-read "${NDKENV_ROOT}/default" ||
  echo system
fi
