#!/usr/bin/env bash
# Summary: Show the current NDK version and its origin
#
# Shows the currently selected NDK version and how it was
# selected. To obtain only the version string, use `ndkenv
# version-name'.

set -e
[ -n "$NDKENV_DEBUG" ] && set -x

echo "$(ndkenv-version-name) (set by $(ndkenv-version-origin))"
