#!/usr/bin/env bash
# Summary: List all NDK versions that contain the given executable
# Usage: ndkenv whence [--path] <command>

set -e
[ -n "$NDKENV_DEBUG" ] && set -x

# Provide ndkenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec ndkenv shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  ndkenv-versions --bare | while read version; do
    path="$(ndkenv-prefix "$version")/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

NDKENV_COMMAND="$1"
if [ -z "$NDKENV_COMMAND" ]; then
  ndkenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$NDKENV_COMMAND")"
[ -n "$result" ] && echo "$result"
