#!/usr/bin/env bash
# Summary: Detect the file that sets the current ndkenv version
set -e
[ -n "$NDKENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.ndk-version" ]; then
      echo "${root}/.ndk-version"
      exit
    elif [ -e "${root}/.ndkenv-version" ]; then
      echo "${root}/.ndkenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$NDKENV_DIR"
[ "$NDKENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${NDKENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${NDKENV_ROOT}/global" ]; then
  echo "${NDKENV_ROOT}/global"
elif [ -e "${NDKENV_ROOT}/default" ]; then
  echo "${NDKENV_ROOT}/default"
else
  echo "$global_version_file"
fi
