#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific NDK version
#
# Usage: ndkenv shell <version>
#        ndkenv shell --unset
#
# Sets a shell-specific NDK version by setting the `NDKENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a NDK version known to ndkenv.
# The special version string `system' will use your default system NDK.
# Run `ndkenv versions' for a list of available NDK versions.

set -e
[ -n "$NDKENV_DEBUG" ] && set -x

# Provide ndkenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec ndkenv-versions --bare
fi

version="$1"
shell="$(basename "${NDKENV_SHELL:-$SHELL}")"

if [ -z "$version" ]; then
  if [ -z "$NDKENV_VERSION" ]; then
    echo "ndkenv: no shell-specific version configured" >&2
    exit 1
  else
    echo "echo \"\$NDKENV_VERSION\""
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  case "$shell" in
  fish )
    echo "set -e NDKENV_VERSION"
    ;;
  * )
    echo "unset NDKENV_VERSION"
    ;;
  esac
  exit
fi

# Make sure the specified version is installed.
if ndkenv-prefix "$version" >/dev/null; then
  case "$shell" in
  fish )
    echo "setenv NDKENV_VERSION \"${version}\""
    ;;
  * )
    echo "export NDKENV_VERSION=\"${version}\""
    ;;
  esac
else
  echo "false"
  exit 1
fi
